{*******************************************************}
{                                                       }
{           CodeGear Delphi Runtime Library             }
{ Copyright(c) 2014 Embarcadero Technologies, Inc.      }
{                                                       }
{*******************************************************}

unit {{Unit}};

interface

uses
{{Uses}};

type
{{Classes}}implementation

procedure RegisterTypes;
begin
{{RegClasses}}end;

initialization
  RegisterTypes;
end.

